/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class MockWhisper extends Whisper{
    int Audio;
    MockWhisper(){
        this.Audio = 2;    
    }
    @Override
    public String transcribe(String a){
        
        if (Audio == 1){
            return "What is the capital of France?";
        }
        else if (Audio == 2){
            return "What is the capital of China?";
        }
        else {
            return "Error: Could not transcribe audio.";
        }
    }
}





class testQuestion {
    //test Question class and methods
    @Test 
    void testSetString() {
        MockWhisper mockwhisper = new MockWhisper();
        Question question = new Question(mockwhisper);
        question.setString("What is the capital of China?");
        
        assertEquals("What is the capital of China?",question.questionStr);
        assertEquals("What is the capital of China?",question.questionContent.getText());
    }
    @Test
    void testToString(){
        MockWhisper mockwhisper = new MockWhisper();
        Question question = new Question(mockwhisper);
        question.setString("What is the capital of China?");

        assertEquals("What is the capital of China?",question.toString());
    }
    @Test
    void testUpdateContent() throws Exception{
        MockWhisper mockwhisper = new MockWhisper();
        Question question = new Question(mockwhisper);
        question.updateContent();
        assertEquals("What is the capital of China?",question.questionContent.getText());

    }
}
